' Gambas module file

Public sInfotext As String

Public Function ActiveFileView(iLR As Integer, fv1 As FileView, fv2 As FileView) As FileView
    'Aktives FileView ermitteln
    If iLR = 1 Then 
        Print "Linkes Feld aktiv: iLR = " & iLR 
        Return fv1
    Else 
        Return fv2
        Print "Rechtes Feld aktiv: iLR = " & iLR
    Endif
End

Public Sub CopyDir(src As String, dst As String)
    'Eine Funktion für Verzeichnisse, damit diese rekursiv und richtig kopiert werden.
    Dim f As String
    
    If Not Exist(dst) Then Mkdir dst
    For Each f In Dir(src)
        If f = "." Or f = ".." Then Continue        ''Wichtig! um aktuellen Ordner und übergeordneten Ordner auszulassen, sonst Dauerschleife
        If Stat(src &/ f).Type = gb.Directory Then 
            CopyDir(src &/ f, dst &/ f)             'Verzeichnis erkennen und Funktion mit neuem Ordnernamen aufrufen
        Else 
            Try Copy src &/ f To dst &/ f           'Dateien kopieren
            If Not Error Then FMain.TextLabel1.Text = "Verzeichnis kopiert. Speicher über Taste R freigeben." 
            If Error Then FMain.TextLabel1.Text = "Verzeichnis kopieren fehlgeschlagen."
        Endif
    Next
End


Public Sub CopySelection(fv As FileView)
    ''Strg C
    Dim s As String
    
    If fv.Selection.Count = 0 Then Return 
    FMain.CopyList.Clear
    For Each s In fv.Selection
        FMain.CopyList.Add(s)
        If FMain.CopyOrMove = 1 Then Print "Kopieren <>  " & s
        If FMain.CopyOrMove = 2 Then Print "Ausschneiden <  " & s
    Next
    FMain.CopySourceDir = fv.Dir
End

Public Sub PasteSelection(fvTarget As FileView)
    ''Strg + V
    Dim s As String
    Dim src As String
    Dim dst As String
    
    If FMain.CopyList.Count = 0 Or FMain.CopySourceDir = "" Then Return 

    For Each s In FMain.CopyList
        Print "Einfügen >  " & s
        src = FMain.CopySourceDir &/ s
        dst = fvTarget.Dir &/ s
        If FMain.CopyOrMove = 1 Then
            If Stat(src).Type = gb.Directory Then 
                Try CopyDir(src, dst)
                If Error Then Print "Fehler beim Verzeichnis kopieren."
            Else 
                Try Copy src To dst
                If Error Then 
                    Print "Fehler beim Kopieren aufgetreten, Datei " & s & " existiert schon."
                    FMain.TextLabel1.Text = "Bereits existierende Dateien wurden nicht kopiert."
                Endif 
                If Not Error Then FMain.TextLabel1.Text = "Kopieren abgeschlossen. Speicher über Taste R freigeben."
            Endif 
        Endif 
        If FMain.CopyOrMove = 2 Then
            Try Move src To dst
            If Not Error Then FMain.TextLabel1.Text = "Verschieben abgeschlossen."
            If Error Then 
                Print "Fehler beim Verschieben, es wird die Fehlerbehandlung probiert."
                Try Copy src To dst
                If Not Error Then Kill src
                If Error Then 
                    Print "Datei " & s & " existiert schon und wird nicht verschoben."
                    FMain.TextLabel1.Text = "Existierende Dateien wurden nicht verschoben."
                Endif 
            Endif 
        Endif
    Next
    If FMain.CopyOrMove = 2 Then 
        Wait 0.8
        FMain.Reset
    Else 
        fvTarget.Reload
    Endif
End


Public Sub Anzeige()
    'Testfunktion
    Message.Info("Die ausgelagerte Funktion wurde aufgerufen", "OK")  'eine Testfunktion
End


Public Sub Einpacken()
    ''Packfunktion um Daten in ein Archiv zu speichern
    If FMain.iLR = 1 Then
        If Exist(User.Home &/ "ARCHIV.zip") Then sInfotext = "Datei / Ordner wurde dem Archiv im Home-Ordner hinzugefügt." 
        If Not Exist(User.Home &/ "ARCHIV.zip") Then sInfotext = "Es wurde ein ARCHIV.zip im Home-Ordner erstellt."
        Try Shell "zip -r ARCHIV.zip " & Shell(FMain.FileView1.Path) Wait 
    Endif
    If FMain.iLR = 2 Then
        If Exist(User.Home &/ "ARCHIV.zip") Then sInfotext = "Datei / Ordner wurde dem Archiv im Home-Ordner hinzugefügt." 
        If Not Exist(User.Home &/ "ARCHIV.zip") Then sInfotext = "Es wurde ein ARCHIV.zip im Home-Ordner erstellt."
        Try Shell "zip -r ARCHIV.zip " & Shell(FMain.FileView2.Path) Wait 
    Endif
End


Public Sub Baum()
    'Baum anzeigen
    Dim hFont As Font
    hFont = Font[", Bold,11"]

    If FMain.bBaum = -1 Then 
        FMain.DirView1.Font = hFont
        FMain.DirView1.Background = FMain.iHindergrund
        FMain.DirView1.Current = FMain.FileView1.Dir
        FMain.DirView1.Visible = True
        FMain.Splitter1.Layout = [18, 50, 4, 30]
        FMain.Splitter3.Layout = [18, 3, 22, 3, 24, 13, 3, 13, 3]
    Endif 
End


Public Sub Killen()
    ''Eine Datei endgültig löschen
    Dim iFrage As Integer
    If FMain.iLR = 1 Then 
         iFrage = Message.Delete("Soll " & FMain.FileView1.Path & " wirklich gelöscht und endgültig zerstört werden?", "JA", "NEIN")
         If iFrage = 1 Then 
             If IsDir(FMain.FileView1.Path) Then Try Rmdir FMain.FileView1.Path Else Try Kill FMain.FileView1.Path
         Else 
             Print "Nix passiert!"
         Endif
    Endif
       'Try Kill FMain.FileView1.Path
    If FMain.iLR = 2 Then
         iFrage = Message.Delete("Soll " & FMain.FileView2.Path & " wirklich gelöscht und endgültig zerstört werden?", "JA", "NEIN")
         If iFrage = 1 Then
             If IsDir(FMain.FileView2.Path) Then Try Rmdir FMain.FileView2.Path Else Try Kill FMain.FileView2.Path
         Else 
             Print "Nix passiert!"
         Endif
    Endif 
    If Error Then Message("Es ist ein Fehler aufgetreten\n oder das Verzeichnis ist nicht leer!")
    FMain.FileView1.Reload 
    FMain.FileView2.Reload
End


Public Sub Spruch()
    ''Spruch des Tages
    Dim x As Integer
    x = Rand(1, 26)
    'Print x
    If x = 1 Then FMain.Label1.Text = "Morgen, morgen nur nicht heute, sagen alle faulen Leute."
    If x = 2 Then FMain.Label1.Text = "Denke nie gedacht zu haben, denn das Denken der Gedanken ist gedankenloses Denken."
    If x = 3 Then FMain.Label1.Text = "Was du heute kannst besorgen, das verschiebe nicht auf Morgen."
    If x = 4 Then FMain.Label1.Text = "Man muss das Eisen schmieden, solange es heiß ist."
    If x = 5 Then FMain.Label1.Text = "Kindermund tut Wahrheit kund."
    If x = 6 Then FMain.Label1.Text = "Was Hänschen nicht lernt, lernt Hans nimmermehr."
    If x = 7 Then FMain.Label1.Text = "Lieber den Spatz in der Hand als die Taube auf dem Dach."
    If x = 8 Then FMain.Label1.Text = "Man soll den Tag nicht vor dem Abend loben."
    If x = 9 Then FMain.Label1.Text = "Kleinvieh macht auch Mist."
    If x = 10 Then FMain.Label1.Text = "Pech im Spiel, Glück in der Liebe."
    If x = 11 Then FMain.Label1.Text = "Ein blindes Huhn findet auch mal ein Korn."
    If x = 12 Then FMain.Label1.Text = "Jeder ist seines Glückes Schmied."
    If x = 13 Then FMain.Label1.Text = "Auf Regen folgt Sonnenschein."
    If x = 14 Then FMain.Label1.Text = "Einem geschenkten Gaul schaut man nicht ins Maul."
    If x = 15 Then FMain.Label1.Text = "Eine Schwalbe macht noch keinen Sommer."
    If x = 16 Then FMain.Label1.Text = "Ist die Katze aus dem Haus, tanzen die Mäuse auf dem Tisch."
    If x = 17 Then FMain.Label1.Text = "In der Not frisst der Teufel fliegen."
    If x = 18 Then FMain.Label1.Text = "Allen Leuten recht getan, ist eine Kunst, die niemand kann."
    If x = 19 Then FMain.Label1.Text = "Besser stumm als dumm."
    If x = 20 Then FMain.Label1.Text = "Ein gebranntes Kind scheut das Feuer." 
    If x = 21 Then FMain.Label1.Text = "Advent, Advent, ein Lichtlein brennt"
    If x = 22 Then FMain.Label1.Text = "Reden ist Silber, schweigen ist Gold."
    If x = 23 Then FMain.Label1.Text = "Hochmut kommt vor dem Fall."
    If x = 24 Then FMain.Label1.Text = "Wer nicht wagt, der nicht gewinnt."
    If x = 25 Then FMain.Label1.Text = "Wer den Pfennig nicht ehrt, ist des Talers nicht wert."
    If x = 26 Then FMain.Label1.Text = "Wo Rauch aufsteigt, da ist auch Feuer."
End

' Public Function FindSftpMount(host As String, usern As String, port As Integer) As String
'     'MOUNTPFAD FINDEN
'     Dim base As String
'     Dim entry As String
'     Dim uid As String
'     
'     uid = Trim(Shell("id -u"))
'     base = "run/user/" & uid & "/gvfs"
'     
'     For Each entry In Dir(base)
'         If entry Like "sftp:host=" & host & "*" Then 
'             If entry Like "*user=" & usern & "*" And entry Like "*port=" & port & "*" Then 
'                 Print base, entry
'                 Return base & "/" & entry
'             Endif
'         Endif
'     Next
'     
'     Return ""
' End

Public Function IsMounted(mountsftp As String) As Boolean
    ' Prüfen ob SFTP Verbindung da und eingehangen ist
    Dim out As String
    
    Shell "mountpoint " & Quote(mountsftp) To out
    
    If InStr(out, "ist ein Einhängepunkt") > 0 Then 
        Return True
    Endif
    
    Return False
End

