' Gambas module file

Public sInfotext As String

'' Hier muss vorher noch ausgiebig getestet werden
' Private $hProc As Process
'  
' Public Sub Verschieben()
'     ''Verschieben Funktion
'     Try $hProc = Shell "mv " & Shell(FMain.QUELLE) & " " & Shell(FMain.ZIEL) For Input Output As "Proc"
'     If Error Then 
'          sInfotext = "Das funktioniert nicht." 
'     Else 
'         FMain.FileView1.Reload()
'         sInfotext = FMain.QUELLE & " >=> wurde verschoben."
'     Endif 
' End
'  
' Public Sub Proc_Read() ' Wenn der Prozess Text ausgibt, können Sie dies für Ihre LED überwachen
'      
' End
'  
' Public Sub Proc_Kill() ' Wenn der Prozess endet
'     'FMain.Spinner1.Stop()
'     
' End
 
' Public Sub Proc_Error(ErrorTxt As String) ' Wenn der Prozess fehlerhaft ist
'     'sInfotext = "Das funktioniert nicht, ein Process Error."
' End

Public Sub Anzeige()
    'Testfunktion
    Message.Info("Die ausgelagerte Funktion wurde aufgerufen", "OK")  'eine Testfunktion
End

Public Sub Einpacken()
    ''Packfunktion um Daten in ein Archiv zu speichern
    If FMain.iLR = 1 Then
        If Exist(User.Home &/ "ARCHIV.zip") Then sInfotext = "Datei / Ordner wurde dem Archiv im Home-Ordner hinzugefügt." 
        If Not Exist(User.Home &/ "ARCHIV.zip") Then sInfotext = "Es wurde ein ARCHIV.zip im Home-Ordner erstellt."
        Try Shell "zip -r ARCHIV.zip " & Shell(FMain.FileView1.Path) Wait 
    Endif
    If FMain.iLR = 2 Then
        If Exist(User.Home &/ "ARCHIV.zip") Then sInfotext = "Datei / Ordner wurde dem Archiv im Home-Ordner hinzugefügt." 
        If Not Exist(User.Home &/ "ARCHIV.zip") Then sInfotext = "Es wurde ein ARCHIV.zip im Home-Ordner erstellt."
        Try Shell "zip -r ARCHIV.zip " & Shell(FMain.FileView2.Path) Wait 
    Endif

End

' Public Sub Verschieben()
'     ''Verschieben Funktion
'     Try Shell "mv " & Shell(FMain.QUELLE) & " " & Shell(FMain.ZIEL) Wait 
'     If Error Or If Process.LastValue <> 0 Then sInfotext = "Das funktioniert nicht." Else sInfotext = FMain.QUELLE & " >=> wurde verschoben."
'     ' Die überarbeitete Funktion statt Quote Shell zu nutzen.
' End

Public Sub Baum()
    'Baum anzeigen
    Dim hFont As Font
    hFont = Font[", Bold,11"]

    If FMain.bBaum = -1 Then 
        FMain.DirView1.Font = hFont
        FMain.DirView1.Background = FMain.iHindergrund
        FMain.DirView1.Current = FMain.FileView1.Dir
        FMain.DirView1.Visible = True
        FMain.Splitter1.Layout = [18, 50, 4, 30]
        FMain.Splitter3.Layout = [18, 3, 22, 3, 24, 13, 3, 13, 3]
    Endif 
End

Public Sub Killen()
    ''Eine Datei endgültig löschen
    Dim iFrage As Integer
    If FMain.iLR = 1 Then 
         iFrage = Message.Delete("Soll " & FMain.FileView1.Path & " wirklich gelöscht und endgültig zerstört werden?", "JA", "NEIN")
         If iFrage = 1 Then 
             If IsDir(FMain.FileView1.Path) Then Try Rmdir FMain.FileView1.Path Else Try Kill FMain.FileView1.Path
         Else 
             Print "Nix passiert!"
         Endif
    Endif
       'Try Kill FMain.FileView1.Path
    If FMain.iLR = 2 Then
         iFrage = Message.Delete("Soll " & FMain.FileView2.Path & " wirklich gelöscht und endgültig zerstört werden?", "JA", "NEIN")
         If iFrage = 1 Then
             If IsDir(FMain.FileView2.Path) Then Try Rmdir FMain.FileView2.Path Else Try Kill FMain.FileView2.Path
         Else 
             Print "Nix passiert!"
         Endif
    Endif 
    If Error Then Message("Es ist ein Fehler aufgetreten\n oder das Verzeichnis ist nicht leer!")
    FMain.FileView1.Reload 
    FMain.FileView2.Reload
End


Public Sub Spruch()
    ''Spruch des Tages
    Dim x As Integer
    x = Rand(1, 26)
    'Print x
    If x = 1 Then FMain.Label1.Text = "Morgen, morgen nur nicht heute, sagen alle faulen Leute."
    If x = 2 Then FMain.Label1.Text = "Denke nie gedacht zu haben, denn das Denken der Gedanken ist gedankenloses Denken."
    If x = 3 Then FMain.Label1.Text = "Was du heute kannst besorgen, das verschiebe nicht auf Morgen."
    If x = 4 Then FMain.Label1.Text = "Man muss das Eisen schmieden, solange es heiß ist."
    If x = 5 Then FMain.Label1.Text = "Kindermund tut Wahrheit kund."
    If x = 6 Then FMain.Label1.Text = "Was Hänschen nicht lernt, lernt Hans nimmermehr."
    If x = 7 Then FMain.Label1.Text = "Lieber den Spatz in der Hand als die Taube auf dem Dach."
    If x = 8 Then FMain.Label1.Text = "Man soll den Tag nicht vor dem Abend loben."
    If x = 9 Then FMain.Label1.Text = "Kleinvieh macht auch Mist."
    If x = 10 Then FMain.Label1.Text = "Pech im Spiel, Glück in der Liebe."
    If x = 11 Then FMain.Label1.Text = "Ein blindes Huhn findet auch mal ein Korn."
    If x = 12 Then FMain.Label1.Text = "Jeder ist seines Glückes Schmied."
    If x = 13 Then FMain.Label1.Text = "Auf Regen folgt Sonnenschein."
    If x = 14 Then FMain.Label1.Text = "Einem geschenkten Gaul schaut man nicht ins Maul."
    If x = 15 Then FMain.Label1.Text = "Eine Schwalbe macht noch keinen Sommer."
    If x = 16 Then FMain.Label1.Text = "Ist die Katze aus dem Haus, tanzen die Mäuse auf dem Tisch."
    If x = 17 Then FMain.Label1.Text = "In der Not frisst der Teufel fliegen."
    If x = 18 Then FMain.Label1.Text = "Allen Leuten recht getan, ist eine Kunst, die niemand kann."
    If x = 19 Then FMain.Label1.Text = "Besser stumm als dumm."
    If x = 20 Then FMain.Label1.Text = "Ein gebranntes Kind scheut das Feuer." 
    If x = 21 Then FMain.Label1.Text = "Advent, Advent, ein Lichtlein brennt"
    If x = 22 Then FMain.Label1.Text = "Reden ist Silber, schweigen ist Gold."
    If x = 23 Then FMain.Label1.Text = "Hochmut kommt vor dem Fall."
    If x = 24 Then FMain.Label1.Text = "Wer nicht wagt, der nicht gewinnt."
    If x = 25 Then FMain.Label1.Text = "Wer den Pfennig nicht ehrt, ist des Talers nicht wert."
    If x = 26 Then FMain.Label1.Text = "Wo Rauch aufsteigt, da ist auch Feuer."
End
